[package]
name = "atc_console"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.20.0"
fltk = { version = "1.3.0", features = ["raw-window-handle"] }
pixels = "0.9.0"